# Change these first
owner: 0xJuancito # Your GitHub organization or username, where this repository lives
repo: inlens-upptime # The name of this repository

sites:
  - name: InLens Website
    url: http://inlens.xyz
  - name: API - Frens
    url: http://inlens.xyz/api/frens?username=LensProtocol

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.inlens.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://inlens.xyz/birdie.svg
  name: Inlens Status
  introTitle: "**Inlens** Status page for the Website and API"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
